# Use postgres/password user/password credentials
version: '3.1'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: location
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "9080:8080"